name: Run CI checks # The name will show up on the GitHub Actions dashboard

on: [pull_request] # This workflow will run only on Pull Requests

env:
  NX_BRANCH: ${{ github.event.number }}

jobs:
  test-affected:
    runs-on: ubuntu-latest
    name: Test Affected
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1
      - run: npm run nx affected --target=test --base=origin/main --parallel
  lint-affected:
    runs-on: ubuntu-latest
    name: Lint Affected
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1
      - run: npm run nx affected --target=lint --base=origin/main
  
  e2e-affected:
    runs-on: ubuntu-latest
    name: e2e Affected
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1
      - run: npm run nx affected --target=e2e --base=origin/main --parallel
      
  build-affected:
    runs-on: ubuntu-latest
    name: Build Affected
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1
      - run: npm run nx affected --target=build --base=origin/main
